#include <stdio.h>

int main(void){

    int i=0;
    int k=4;
    for(i = 0; i < k; ++i){
        printf("Dicks NEJNENJNEJNEJNEJNJENJENEJNJENJENJNEJNEJNEJNJENEJNJENJENJEJNENEJNEJNENENJENJENJENJNEJNEJNEJNEJNEJNEJNJENJENNJEJENJENJENENEJNJENnfjkdgiusdCFGURDKSNBDHIJHJDJDSAHOHIeøfwjøewkNFEWNiofciodsjJP9OFREDRIK DFRERFAEWEDFWRDDEDEDEEDE FREFDNOSVIHREFIOVNBFGDOJFNOIVFNOIBMKLDFJJJJVVKFKFKKFKFKEOKWPOACJNIE\n");
    }
  return 0;
}
